//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub mod prelude;

pub mod device_metadata;
pub mod ingest_batches;
pub mod sea_orm_active_enums;
pub mod spatial_ref_sys;
pub mod trips;
pub mod user_activity_ingest;
pub mod user_locations_ingest;
pub mod user_visits_ingest;
pub mod users;
