//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "trips")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    #[sea_orm(column_type = "custom(\"geometry\")")]
    pub geometry: String,
    #[sea_orm(column_type = "custom(\"geometry\")")]
    pub bounding_box: String,
    pub start_time: DateTimeWithTimeZone,
    pub end_time: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Double")]
    pub distance_meters: f64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub points: Option<Vec<u8>>,
    pub processed: bool,
    #[sea_orm(column_type = "JsonBinary")]
    pub osm_way_ids: Json,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub route_match_trace: Option<Vec<u8>>,
    pub label: Option<String>,
    pub notes: Option<String>,
    pub geo_json: Option<String>,
    pub last_modified: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
