//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "user_locations_ingest")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub batch_id: i32,
    #[sea_orm(column_type = "Double")]
    pub latitude: f64,
    #[sea_orm(column_type = "Double")]
    pub longitude: f64,
    #[sea_orm(column_type = "Double", nullable)]
    pub altitude: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub horizontal_accuracy: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub vertical_accuracy: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub speed_accuracy: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub bearing_accuracy: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub speed: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub bearing: Option<f64>,
    pub date_time: DateTimeWithTimeZone,
    pub is_mock_location: Option<bool>,
    pub floor_level: Option<i32>,
    pub battery_level: Option<i32>,
    pub network_type: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ingest_batches::Entity",
        from = "Column::BatchId",
        to = "super::ingest_batches::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    IngestBatches,
}

impl Related<super::ingest_batches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IngestBatches.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
