//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "user_visits_ingest")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub batch_id: Uuid,
    #[sea_orm(column_type = "Double")]
    pub latitude: f64,
    #[sea_orm(column_type = "Double")]
    pub longitude: f64,
    #[sea_orm(column_type = "Double", nullable)]
    pub horizontal_accuracy: Option<f64>,
    pub arrival_date_time: DateTimeWithTimeZone,
    pub departure_date_time: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ingest_batches::Entity",
        from = "Column::BatchId",
        to = "super::ingest_batches::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    IngestBatches,
}

impl Related<super::ingest_batches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IngestBatches.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
