// @generated by protoc-gen-connect-es v1.5.0 with parameter "target=ts"
// @generated from file chronotopia.proto (package chronotopia, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { RequestParameters, RouteMatchTrace, Trips } from "./chronotopia_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chronotopia.Chronotopia
 */
export const Chronotopia = {
  typeName: "chronotopia.Chronotopia",
  methods: {
    /**
     * @generated from rpc chronotopia.Chronotopia.GetTrips
     */
    getTrips: {
      name: "GetTrips",
      I: RequestParameters,
      O: Trips,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chronotopia.Chronotopia.GetRouteMatchTrace
     */
    getRouteMatchTrace: {
      name: "GetRouteMatchTrace",
      I: Empty,
      O: RouteMatchTrace,
      kind: MethodKind.Unary,
    },
  }
} as const;

