// @generated by protoc-gen-connect-es v1.5.0 with parameter "target=ts"
// @generated from file chronotopia.proto (package chronotopia, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { LatLon } from "./common_pb.js";
import { MethodKind, StringValue } from "@bufbuild/protobuf";
import { ConnectivityRequest, PathfindingDebugInfo, WindowDebugRequest } from "./chronotopia_pb.js";

/**
 * @generated from service chronotopia.Chronotopia
 */
export const Chronotopia = {
  typeName: "chronotopia.Chronotopia",
  methods: {
    /**
     * @generated from rpc chronotopia.Chronotopia.OSMNetworkAroundPoint
     */
    oSMNetworkAroundPoint: {
      name: "OSMNetworkAroundPoint",
      I: LatLon,
      O: StringValue,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chronotopia.Chronotopia.AnalyzeSegmentConnectivity
     */
    analyzeSegmentConnectivity: {
      name: "AnalyzeSegmentConnectivity",
      I: ConnectivityRequest,
      O: StringValue,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chronotopia.Chronotopia.DebugWindowPathFinding
     */
    debugWindowPathFinding: {
      name: "DebugWindowPathFinding",
      I: WindowDebugRequest,
      O: PathfindingDebugInfo,
      kind: MethodKind.Unary,
    },
  }
} as const;

