// @generated by protoc-gen-connect-es v1.5.0 with parameter "target=ts"
// @generated from file common.proto (package chronotopia, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PlanRouteRequest, PlanRouteResponse } from "./common_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chronotopia.Common
 */
export const Common = {
  typeName: "chronotopia.Common",
  methods: {
    /**
     * Plan route between points
     *
     * @generated from rpc chronotopia.Common.PlanRoute
     */
    planRoute: {
      name: "PlanRoute",
      I: PlanRouteRequest,
      O: PlanRouteResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

