// @generated by protoc-gen-connect-es v1.5.0 with parameter "target=ts"
// @generated from file ingest.proto (package chronotopia, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeviceMetadata, GoogleMapsTimelineExport, IngestBatch, IngestResponse } from "./ingest_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chronotopia.Ingest
 */
export const Ingest = {
  typeName: "chronotopia.Ingest",
  methods: {
    /**
     * @generated from rpc chronotopia.Ingest.SubmitBatch
     */
    submitBatch: {
      name: "SubmitBatch",
      I: IngestBatch,
      O: IngestResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chronotopia.Ingest.SubmitDeviceMetadata
     */
    submitDeviceMetadata: {
      name: "SubmitDeviceMetadata",
      I: DeviceMetadata,
      O: IngestResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chronotopia.Ingest.SubmitGoogleMapsTimelineExport
     */
    submitGoogleMapsTimelineExport: {
      name: "SubmitGoogleMapsTimelineExport",
      I: GoogleMapsTimelineExport,
      O: IngestResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

