// @generated by protoc-gen-connect-es v1.5.0 with parameter "target=ts"
// @generated from file trips.proto (package chronotopia, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetTripDetailsRequest, GetTripDetailsResponse, GetTripsForUserRequest, GetTripsForUserResponse, GetUserProcessingStateResponse, TriggerProcessingResponse } from "./trips_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chronotopia.Trips
 */
export const Trips = {
  typeName: "chronotopia.Trips",
  methods: {
    /**
     * Get trips for the authenticated user
     *
     * @generated from rpc chronotopia.Trips.GetTripsForUser
     */
    getTripsForUser: {
      name: "GetTripsForUser",
      I: GetTripsForUserRequest,
      O: GetTripsForUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Get processing state for the authenticated user
     *
     * @generated from rpc chronotopia.Trips.GetUserProcessingState
     */
    getUserProcessingState: {
      name: "GetUserProcessingState",
      I: Empty,
      O: GetUserProcessingStateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Trigger processing for the authenticated user
     *
     * @generated from rpc chronotopia.Trips.TriggerProcessing
     */
    triggerProcessing: {
      name: "TriggerProcessing",
      I: Empty,
      O: TriggerProcessingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Get detailed trip information
     *
     * @generated from rpc chronotopia.Trips.GetTripDetails
     */
    getTripDetails: {
      name: "GetTripDetails",
      I: GetTripDetailsRequest,
      O: GetTripDetailsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

