services:
  db:
    image: postgis/postgis:17-3.5
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      PGUSER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
    network_mode: "host"

volumes:
  pgdata:
