// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: ingest.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - chronotopia.Ingest

/// Namespace containing generated types for the "chronotopia.Ingest" service.
internal enum Chronotopia_Ingest {
    /// Service descriptor for the "chronotopia.Ingest" service.
    internal static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "chronotopia.Ingest")
    /// Namespace for method metadata.
    internal enum Method {
        /// Namespace for "SubmitBatch" metadata.
        internal enum SubmitBatch {
            /// Request type for "SubmitBatch".
            internal typealias Input = Chronotopia_IngestBatch
            /// Response type for "SubmitBatch".
            internal typealias Output = Chronotopia_IngestResponse
            /// Descriptor for "SubmitBatch".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "chronotopia.Ingest"),
                method: "SubmitBatch"
            )
        }
        /// Namespace for "SubmitDeviceMetadata" metadata.
        internal enum SubmitDeviceMetadata {
            /// Request type for "SubmitDeviceMetadata".
            internal typealias Input = Chronotopia_DeviceMetadata
            /// Response type for "SubmitDeviceMetadata".
            internal typealias Output = Chronotopia_IngestResponse
            /// Descriptor for "SubmitDeviceMetadata".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "chronotopia.Ingest"),
                method: "SubmitDeviceMetadata"
            )
        }
        /// Namespace for "SubmitGoogleMapsTimelineExport" metadata.
        internal enum SubmitGoogleMapsTimelineExport {
            /// Request type for "SubmitGoogleMapsTimelineExport".
            internal typealias Input = Chronotopia_GoogleMapsTimelineExport
            /// Response type for "SubmitGoogleMapsTimelineExport".
            internal typealias Output = Chronotopia_IngestResponse
            /// Descriptor for "SubmitGoogleMapsTimelineExport".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "chronotopia.Ingest"),
                method: "SubmitGoogleMapsTimelineExport"
            )
        }
        /// Descriptors for all methods in the "chronotopia.Ingest" service.
        internal static let descriptors: [GRPCCore.MethodDescriptor] = [
            SubmitBatch.descriptor,
            SubmitDeviceMetadata.descriptor,
            SubmitGoogleMapsTimelineExport.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "chronotopia.Ingest" service.
    internal static let chronotopia_Ingest = GRPCCore.ServiceDescriptor(fullyQualifiedService: "chronotopia.Ingest")
}

// MARK: chronotopia.Ingest (server)

extension Chronotopia_Ingest {
    /// Streaming variant of the service protocol for the "chronotopia.Ingest" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    internal protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "SubmitBatch" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Chronotopia_IngestBatch` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Chronotopia_IngestResponse` messages.
        func submitBatch(
            request: GRPCCore.StreamingServerRequest<Chronotopia_IngestBatch>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Chronotopia_IngestResponse>

        /// Handle the "SubmitDeviceMetadata" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Chronotopia_DeviceMetadata` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Chronotopia_IngestResponse` messages.
        func submitDeviceMetadata(
            request: GRPCCore.StreamingServerRequest<Chronotopia_DeviceMetadata>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Chronotopia_IngestResponse>

        /// Handle the "SubmitGoogleMapsTimelineExport" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Chronotopia_GoogleMapsTimelineExport` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Chronotopia_IngestResponse` messages.
        func submitGoogleMapsTimelineExport(
            request: GRPCCore.StreamingServerRequest<Chronotopia_GoogleMapsTimelineExport>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Chronotopia_IngestResponse>
    }

    /// Service protocol for the "chronotopia.Ingest" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    internal protocol ServiceProtocol: Chronotopia_Ingest.StreamingServiceProtocol {
        /// Handle the "SubmitBatch" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Chronotopia_IngestBatch` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Chronotopia_IngestResponse` message.
        func submitBatch(
            request: GRPCCore.ServerRequest<Chronotopia_IngestBatch>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Chronotopia_IngestResponse>

        /// Handle the "SubmitDeviceMetadata" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Chronotopia_DeviceMetadata` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Chronotopia_IngestResponse` message.
        func submitDeviceMetadata(
            request: GRPCCore.ServerRequest<Chronotopia_DeviceMetadata>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Chronotopia_IngestResponse>

        /// Handle the "SubmitGoogleMapsTimelineExport" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Chronotopia_GoogleMapsTimelineExport` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Chronotopia_IngestResponse` message.
        func submitGoogleMapsTimelineExport(
            request: GRPCCore.ServerRequest<Chronotopia_GoogleMapsTimelineExport>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Chronotopia_IngestResponse>
    }

    /// Simple service protocol for the "chronotopia.Ingest" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    internal protocol SimpleServiceProtocol: Chronotopia_Ingest.ServiceProtocol {
        /// Handle the "SubmitBatch" method.
        ///
        /// - Parameters:
        ///   - request: A `Chronotopia_IngestBatch` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Chronotopia_IngestResponse` to respond with.
        func submitBatch(
            request: Chronotopia_IngestBatch,
            context: GRPCCore.ServerContext
        ) async throws -> Chronotopia_IngestResponse

        /// Handle the "SubmitDeviceMetadata" method.
        ///
        /// - Parameters:
        ///   - request: A `Chronotopia_DeviceMetadata` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Chronotopia_IngestResponse` to respond with.
        func submitDeviceMetadata(
            request: Chronotopia_DeviceMetadata,
            context: GRPCCore.ServerContext
        ) async throws -> Chronotopia_IngestResponse

        /// Handle the "SubmitGoogleMapsTimelineExport" method.
        ///
        /// - Parameters:
        ///   - request: A `Chronotopia_GoogleMapsTimelineExport` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Chronotopia_IngestResponse` to respond with.
        func submitGoogleMapsTimelineExport(
            request: Chronotopia_GoogleMapsTimelineExport,
            context: GRPCCore.ServerContext
        ) async throws -> Chronotopia_IngestResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
extension Chronotopia_Ingest.StreamingServiceProtocol {
    internal func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Chronotopia_Ingest.Method.SubmitBatch.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Chronotopia_IngestBatch>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Chronotopia_IngestResponse>(),
            handler: { request, context in
                try await self.submitBatch(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Chronotopia_Ingest.Method.SubmitDeviceMetadata.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Chronotopia_DeviceMetadata>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Chronotopia_IngestResponse>(),
            handler: { request, context in
                try await self.submitDeviceMetadata(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Chronotopia_Ingest.Method.SubmitGoogleMapsTimelineExport.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Chronotopia_GoogleMapsTimelineExport>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Chronotopia_IngestResponse>(),
            handler: { request, context in
                try await self.submitGoogleMapsTimelineExport(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
extension Chronotopia_Ingest.ServiceProtocol {
    internal func submitBatch(
        request: GRPCCore.StreamingServerRequest<Chronotopia_IngestBatch>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Chronotopia_IngestResponse> {
        let response = try await self.submitBatch(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func submitDeviceMetadata(
        request: GRPCCore.StreamingServerRequest<Chronotopia_DeviceMetadata>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Chronotopia_IngestResponse> {
        let response = try await self.submitDeviceMetadata(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func submitGoogleMapsTimelineExport(
        request: GRPCCore.StreamingServerRequest<Chronotopia_GoogleMapsTimelineExport>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Chronotopia_IngestResponse> {
        let response = try await self.submitGoogleMapsTimelineExport(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
extension Chronotopia_Ingest.SimpleServiceProtocol {
    internal func submitBatch(
        request: GRPCCore.ServerRequest<Chronotopia_IngestBatch>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Chronotopia_IngestResponse> {
        return GRPCCore.ServerResponse<Chronotopia_IngestResponse>(
            message: try await self.submitBatch(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func submitDeviceMetadata(
        request: GRPCCore.ServerRequest<Chronotopia_DeviceMetadata>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Chronotopia_IngestResponse> {
        return GRPCCore.ServerResponse<Chronotopia_IngestResponse>(
            message: try await self.submitDeviceMetadata(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func submitGoogleMapsTimelineExport(
        request: GRPCCore.ServerRequest<Chronotopia_GoogleMapsTimelineExport>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Chronotopia_IngestResponse> {
        return GRPCCore.ServerResponse<Chronotopia_IngestResponse>(
            message: try await self.submitGoogleMapsTimelineExport(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: chronotopia.Ingest (client)

extension Chronotopia_Ingest {
    /// Generated client protocol for the "chronotopia.Ingest" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    internal protocol ClientProtocol: Sendable {
        /// Call the "SubmitBatch" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Chronotopia_IngestBatch` message.
        ///   - serializer: A serializer for `Chronotopia_IngestBatch` messages.
        ///   - deserializer: A deserializer for `Chronotopia_IngestResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func submitBatch<Result>(
            request: GRPCCore.ClientRequest<Chronotopia_IngestBatch>,
            serializer: some GRPCCore.MessageSerializer<Chronotopia_IngestBatch>,
            deserializer: some GRPCCore.MessageDeserializer<Chronotopia_IngestResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Chronotopia_IngestResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "SubmitDeviceMetadata" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Chronotopia_DeviceMetadata` message.
        ///   - serializer: A serializer for `Chronotopia_DeviceMetadata` messages.
        ///   - deserializer: A deserializer for `Chronotopia_IngestResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func submitDeviceMetadata<Result>(
            request: GRPCCore.ClientRequest<Chronotopia_DeviceMetadata>,
            serializer: some GRPCCore.MessageSerializer<Chronotopia_DeviceMetadata>,
            deserializer: some GRPCCore.MessageDeserializer<Chronotopia_IngestResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Chronotopia_IngestResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "SubmitGoogleMapsTimelineExport" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Chronotopia_GoogleMapsTimelineExport` message.
        ///   - serializer: A serializer for `Chronotopia_GoogleMapsTimelineExport` messages.
        ///   - deserializer: A deserializer for `Chronotopia_IngestResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func submitGoogleMapsTimelineExport<Result>(
            request: GRPCCore.ClientRequest<Chronotopia_GoogleMapsTimelineExport>,
            serializer: some GRPCCore.MessageSerializer<Chronotopia_GoogleMapsTimelineExport>,
            deserializer: some GRPCCore.MessageDeserializer<Chronotopia_IngestResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Chronotopia_IngestResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "chronotopia.Ingest" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    internal struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        internal init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "SubmitBatch" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Chronotopia_IngestBatch` message.
        ///   - serializer: A serializer for `Chronotopia_IngestBatch` messages.
        ///   - deserializer: A deserializer for `Chronotopia_IngestResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func submitBatch<Result>(
            request: GRPCCore.ClientRequest<Chronotopia_IngestBatch>,
            serializer: some GRPCCore.MessageSerializer<Chronotopia_IngestBatch>,
            deserializer: some GRPCCore.MessageDeserializer<Chronotopia_IngestResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Chronotopia_IngestResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Chronotopia_Ingest.Method.SubmitBatch.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "SubmitDeviceMetadata" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Chronotopia_DeviceMetadata` message.
        ///   - serializer: A serializer for `Chronotopia_DeviceMetadata` messages.
        ///   - deserializer: A deserializer for `Chronotopia_IngestResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func submitDeviceMetadata<Result>(
            request: GRPCCore.ClientRequest<Chronotopia_DeviceMetadata>,
            serializer: some GRPCCore.MessageSerializer<Chronotopia_DeviceMetadata>,
            deserializer: some GRPCCore.MessageDeserializer<Chronotopia_IngestResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Chronotopia_IngestResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Chronotopia_Ingest.Method.SubmitDeviceMetadata.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "SubmitGoogleMapsTimelineExport" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Chronotopia_GoogleMapsTimelineExport` message.
        ///   - serializer: A serializer for `Chronotopia_GoogleMapsTimelineExport` messages.
        ///   - deserializer: A deserializer for `Chronotopia_IngestResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func submitGoogleMapsTimelineExport<Result>(
            request: GRPCCore.ClientRequest<Chronotopia_GoogleMapsTimelineExport>,
            serializer: some GRPCCore.MessageSerializer<Chronotopia_GoogleMapsTimelineExport>,
            deserializer: some GRPCCore.MessageDeserializer<Chronotopia_IngestResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Chronotopia_IngestResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Chronotopia_Ingest.Method.SubmitGoogleMapsTimelineExport.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension Chronotopia_Ingest.ClientProtocol {
    /// Call the "SubmitBatch" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Chronotopia_IngestBatch` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func submitBatch<Result>(
        request: GRPCCore.ClientRequest<Chronotopia_IngestBatch>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Chronotopia_IngestResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.submitBatch(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Chronotopia_IngestBatch>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Chronotopia_IngestResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SubmitDeviceMetadata" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Chronotopia_DeviceMetadata` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func submitDeviceMetadata<Result>(
        request: GRPCCore.ClientRequest<Chronotopia_DeviceMetadata>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Chronotopia_IngestResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.submitDeviceMetadata(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Chronotopia_DeviceMetadata>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Chronotopia_IngestResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SubmitGoogleMapsTimelineExport" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Chronotopia_GoogleMapsTimelineExport` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func submitGoogleMapsTimelineExport<Result>(
        request: GRPCCore.ClientRequest<Chronotopia_GoogleMapsTimelineExport>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Chronotopia_IngestResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.submitGoogleMapsTimelineExport(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Chronotopia_GoogleMapsTimelineExport>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Chronotopia_IngestResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension Chronotopia_Ingest.ClientProtocol {
    /// Call the "SubmitBatch" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func submitBatch<Result>(
        _ message: Chronotopia_IngestBatch,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Chronotopia_IngestResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Chronotopia_IngestBatch>(
            message: message,
            metadata: metadata
        )
        return try await self.submitBatch(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SubmitDeviceMetadata" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func submitDeviceMetadata<Result>(
        _ message: Chronotopia_DeviceMetadata,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Chronotopia_IngestResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Chronotopia_DeviceMetadata>(
            message: message,
            metadata: metadata
        )
        return try await self.submitDeviceMetadata(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SubmitGoogleMapsTimelineExport" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func submitGoogleMapsTimelineExport<Result>(
        _ message: Chronotopia_GoogleMapsTimelineExport,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Chronotopia_IngestResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Chronotopia_GoogleMapsTimelineExport>(
            message: message,
            metadata: metadata
        )
        return try await self.submitGoogleMapsTimelineExport(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}